apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    namespace: brincadeirinha
spec:
    selector:
        matchLabels:
            app: nginx-deploy
    template:
        metadata:
            labels:
                app: nginx-deploy
        spec:
            containers:
                - name: nginx
                  image: nginx-mysql-client
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 80
