apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    namespace: brincadeirinha
spec:
    type: NodePort
    selector:
        app: nginx-deploy
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
