apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deploy
    namespace: brincadeirinha
spec:
    selector:
        matchLabels:
            app: mysql-deploy
    template:
        metadata:
            labels:
                app: mysql-deploy
        spec:
            containers:
                - name: mysql
                  image: mysql:8.0
                  ports:
                      - containerPort: 3306
                  args: [--default-authentication-plugin=mysql_native_password]
                  env:
                      - name: MYSQL_USER
                        value: "docker"
                      - name: MYSQL_PASSWORD
                        value: "docker"
                      - name: MYSQL_DATABASE
                        value: "docker"
                      - name: MYSQL_ROOT_PASSWORD
                        value: "docker"
